### PR TITLE
Stream desynchronization fix

### LINKED ISSUE #6: XLinkOpenStream StreamId desynchronization
`XLinkOpenStream` has an issue where if both host and device try to open streams, `streamId` can get "desynchronized`.
Example:
XLinkOpenStream1

The above diagram shows how host tries to open stream `A` and device stream `B`, but the results are that both streams now point to same IDs, which results in all data transfers being delivered to wrong locations.

Possible solution is to replace the creation of "unique" stream ID on remote with creating one locally for local conversion between ID<->name while replace using stream name as an unique ID. 

Events would then be sent with name instead of ID, but this doesn't diverge too much from current architecture, as stream name has a fixed place in event header already.

### PR DESCRIPTION
**Pull request by themarpe**
Backwards compatible for for desynchronization of opening streams from both device and host side.

Closes #6

 - Added a test for future reference.
 - The fix itself is in `shared/src/XLinkDispatcherImpl.c`

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
Sweet, thanks!  This works great for me on PoE - no longer are there XLink issues on launch.  Tested a large number of cameras over POE, and where previously at least 50% would have errors, now not a single one did:

image

dfgafdasdfasdf

File: shared/src/XLinkDispatcherImpl.c [hunk 1]
```diff
@@ -176,6 +176,13 @@ int dispatcherLocalEventGetResponse(xLinkEvent_t* event, xLinkEvent_t* response)
         }
         case XLINK_CREATE_STREAM_REQ:
         {
+
+            // If Host side - this event happens when host tries to send an OpenStream request to device.
+            // Generate a streamId (and not relly on device to do it) and send that to the device.
```
Comment (szabi-luxonis) [inline shared/src/XLinkDispatcherImpl.c:181]: typo: rely

**Review by szabi-luxonis — APPROVED** [review]
LGTM

File: shared/src/XLinkDispatcherImpl.c (hunk 1 above)
Comment (themarpe) [reply shared/src/XLinkDispatcherImpl.c:181]: Thanks - was wondering that this looks a tad odd:D
Fixing..
